M48
; DRILL file {KiCad 7.0.1} date Thu Aug 24 09:27:24 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-24T09:27:24-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
%
G90
G05
T1
X3.8215Y-6.8993
X4.049Y-6.8993
T2
X4.6606Y-6.64
X4.7197Y-6.5377
T0
M30
