M48
; DRILL file {KiCad 7.0.2} date Mon Jul 17 20:56:44 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-17T20:56:44-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
%
G90
G05
T1
X6.9305Y-6.2013
X7.1581Y-6.2013
T2
X7.7697Y-5.9419
X7.8287Y-5.8396
T0
M30
